const navLinks = [
    {
      name: "Work",
      link: "#work",
    },
    {
      name: "Experience",
      link: "#experience",
    },
    {
      name: "Skills",
      link: "#skills",
    },
    {
      name: "Testimonials",
      link: "#testimonials",
    },
  ];

  const categoryEmojis = {
  "Loaves, Rolls, Buns": "🥖",
  "Candies & Cookies": "🍪",
  "Wedges, Wheels, Loaves, Logs": "🧀",
  "Dip/Spread": "🥣",
  "Packaged Fish, Meat, Fruit & Veg": "🥫",
  "Entrées & Sides": "🍽️",
  "BBQ, Pasta, Simmer": "🍝",
  "Chips, Crackers & Crunchy Bites": "🍟",
  "Entrées & Center of Plate": "🥘",
  "Sliced Bread": "🍞",
  "Sweet Stuff": "🍰",
  "Veggies": "🥦",
  "Bars, Jerky &… Surprises": "🍫",
  "Salads, Soups & Sides": "🥗",
  "Fruits": "🍎",
  "Nuts, Dried Fruits, Seeds": "🥜",
  "Wraps, Burritos & Sandwiches": "🌯",
  "Cream and Creamy Cheeses": "🧈",
  "Bagels": "🥯",
  "Soup, Chili & Meals": "🍲",
  "Chicken & Turkey": "🍗",
  "Oils & Vinegars": "🫒",
  "Cool Desserts": "🍨",
  "Slices, Shreds, Crumbles": "🧀",
  "Eggs": "🥚",
  "Yogurt, etc.": "🍦",
  "Tortillas & Flatbreads": "🫓",
  "Cereals": "🥣",
  "For Baking & Cooking": "🧁",
  "Dressing & Seasoning": "🧂",
  "Pastas & Grains": "🍜",
  "Spices": "🌶️",
  "Beef, Pork & Lamb": "🥩",
  "Nut Butters & Fruit Spreads": "🥜",
  "Appetizers": "🧆",
  "Plant-based Protein": "🌱",
  "Fruit & Vegetables": "🥕",
  "Salsa & Hot Sauce": "🌶️",
  "Butter": "🧈",
  "Condiments": "🧃",
  "Fish & Seafood": "🐟",
  "Milk & Cream": "🥛",
  "Honeys, Syrups & Nectars": "🍯",
  "Juices & More": "🧃",
  "Non-Dairy Bev": "🥥",
  "Coffee & Tea": "☕",
  "Wine, Beer & Liquor": "🍷",
  "Water (Sparkling & Still)": "💧",
  "Pet Stuff": "🐾",
  "For the Face & Body": "🧴",
  "Household Essentials": "🧼",
  "Nutritional Supplements": "💊",
  "Sodas & Mixers": "🥤",
  "Flowers & Plants": "🌸",
  "default": "🛒"
};


export {navLinks, categoryEmojis};